// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:template_project/app/data/models/alias/alias_model.dart';
import 'package:template_project/app/data/models/chat_user_model/chat_user_model.dart';
import 'package:template_project/app/data/models/message/message_model.dart';
import 'package:template_project/app/data/models/user/user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AliasModelAdapter());
    registerAdapter(ChatUserModelAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AliasModelAdapter());
    registerAdapter(ChatUserModelAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
